apiVersion: apps/v1
kind: Deployment
metadata:
  name: relayer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relayer
  template:
    metadata:
      labels:
        app: relayer
    spec:
      imagePullSecrets:
        - name: docker-credentials
      containers:
        - name: wormhole-spy
          image: intothefathom/splyce.solana.wormhole.relayer:v0.0.1-dev
          imagePullPolicy: Always
          ports:
            - containerPort: 7073
          env:
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "relayer-db"
            - name: POSTGRES_HOST
              value: "postgres"
            - name: POSTGRES_PORT
              value: "5432"
            - name: SPY_HOST
              value: "wormhole-spy"
            - name: SPY_PORT
              value: "7073"
            - name: REDIS_HOST
              value: "redis.db"
            - name: REDIS_PORT
              value: "6379"
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: solana-relayer-secret
                  key: PRIVATE_KEY
            - name: STARTING_SEQUENCE_CHAIN_10002
              value: "4640"
            - name: STARTING_SEQUENCE_CHAIN_4
              value: "7000"
            - name: LOG_LEVEL
              value: "debug"
            - name: LOG_TIMESTAMP
              value: "true"
            - name: LOG_TAG
              value: "false"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"